### ISSUE TITLE
cmd_arr[0] : (null)

### ISSUE THREAD

**Issue by ankasamanyan** [ankasamanyan/minishell#2]
----halp----
=>   input : ls
=>   cmd_arr[0] : (null) 

![IMAGE 2022-11-27 23:39:15](https://user-images.githubusercontent.com/89840461/204163549-a8344cf9-c298-4c93-b8ad-c010381282f5.jpg)

**Comment by mulain** [comment]
Weird. I can't reproduce it:
![image](https://user-images.githubusercontent.com/30655804/204198878-381d31f2-f8e7-4fb7-8a6f-207637261825.png)
