### ISSUE TITLE
uninitialized cmd 

### ISSUE THREAD

**Issue by ankasamanyan** [ankasamanyan/minishell#3]
`cmd` in `t_pair's` is currently pointing to nothing I guess, Idk where to initialize it
halp?

<img width="304" alt="image" src="https://user-images.githubusercontent.com/89840461/204244664-a0c6a10a-4577-4b12-8b0e-39f96ff77f03.png">

**Comment by mulain** [comment]
Updated make_commands to include this.

**Comment by ankasamanyan** [comment]
Fanksssss
<img width="463" alt="doggo" src="https://user-images.githubusercontent.com/89840461/204270094-6855a3b2-7102-47b0-bf03-52c78e170ec3.png">
